version: '3.9'

services:
  socket-server:
    build:
      context: ../socket-server
    ports:
      - "8080:8080"
    networks:
      - app-network

  web-client:
    build:
      context: ../web-client
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - VITE_WS_URL=ws://socket-server:8080/test
    depends_on:
      - socket-server

networks:
  app-network:
    driver: bridge